# This file is for ease of use in development. This configuration mirrors
# the .docker/development.yml config. You may edit this as you wish, but
# DO NOT COMMIT your changes to source control.

version: '2'
services:
  db:
    extends:
      file: .docker/registration.yml
      service: db
    ports:
      - "8027:27017"
    volumes:
      - /data/contest:/data/db
  webapp:
    extends:
      file: .docker/registration.yml
      service: webapp
    volumes:
      - .:/webapp
    ports:
      - "8080:80"
    environment:
      FLASK_CONFIG: '/webapp/config/development.py'
      FLASK_DEBUG: 1
