version: '2'
services:

  #
  #   Registration
  #

  # Registration system database
  db:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /data/contest:/data/db

  # Registration system webapp
  webapp:
    build: .
    image: fsu-acm/contest-server
    environment:
      - FLASK_CONFIG=/webapp/config/production.py
    ports:
      - "8080:80"
    volumes:
      - /acm/contest/share:/webapp/share
    depends_on:
      - db

  #
  #   Domjudge
  #

  # Domjudge database
  domdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DOM_PASS}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./config/domdb:/etc/mysql/conf.d
      - /private/var/lib/containers/domjudge_db:/var/lib/mysql

  # Domjudge server
  domserver:
    image: andrewsosa/domjudge-domserver
    environment:
      - DOMJUDGE_DB_HOST=domdb
      - DOMJUDGE_DB_PASSWORD=${DOM_PASS}
      - DOMJUDGE_DB_ROOT_PASSWORD=${DOM_PASS}
    ports:
      - "8081:80"
    depends_on:
     - domdb

  # Judgehost
  judgehost:
    image: andrewsosa/domjudge-judgehost
    privileged: true
    cap_add:
        - SYS_ADMIN
    environment:
      - DOMSERVER_HOST=domserver/api
      - DOMSERVER_USER=judgehost
      - DOMSERVER_PASSWORD=${DOM_PASS}
