version: '2'
services:

  # Proxy server [entry point] TODO: SSL
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      # - /etc/nginx/certs
      # - /etc/nginx/vhost.d
      # - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      # - "443:443"

  # Registration system database
  db:
    extends:
      file: registration.yml
      service: db
    volumes:
      - /data/contest:/data/db

  # Registration system webapp
  webapp:
    extends:
      file: registration.yml
      service: webapp
    environment:
      FLASK_CONFIG: '/webapp/config/production.py'
      VIRTUAL_HOST: 'contest.acmatfsu.org'

  # Domjudge server
  domserver:
    extends:
      file: domserver.yml
      service: domserver
    environment:
      VIRTUAL_HOST: 'domjudge.acmatfsu.org'

  # Domjudge database
  domdb:
    extends:
      file: domserver.yml
      service: domdb
    environment:
      # VIRTUAL_HOST: 'db.domjudge.acmatfsu.org'
