version: '2'
services:
  webapp:
    build: ..
    image: contest-unf
    restart: always
    ports:
      - "8083:80"
  db:
    image: "mongo"
    restart: "always"
    ports:
      - "127.0.0.1:8027:27017"
